# Needed so we can install snaps
sudo: required
dist: trusty

language: cpp

branches:
  only:
  - staging
  - trying
  - master
  # release branch
  - /^release\/[\d\.]+$/
  # release tag
  - /^v[\d\.]+$/

stages:
- name: test
  # don't test on pushes to master or release pull requests or tag events
  # TODO: enable release pull request testing when we have more CI power
  if: NOT (( branch = master AND type = push )
             OR ( head_branch =~ ^release/[\d\.]+$ ))
      AND tag IS blank
- name: upload to ppa:mir-team
  if: type = push
      AND repo = MirServer/mir
      AND ( branch = master
            OR branch =~ ^release/[\d\.]+$
            OR tag =~ ^v[\d\.]+$ )

env:
  global:
    # SPREAD_LINODE_KEY
  - secure: RCoJlG7Su7btAQDHoqDDkIGj3pXatGPeUnBQ3ZC2nfw40Tg7m3Rp21igW02x4hjWH7BtHM7AzyyAbr7Z87MA1KYVZ6bc1+LXjByiKWH+rurXchJupWusplZR1/6kbPMsOswH9bPf72FzfoG+Kt7Xg+14ePu34x0lvLHqIPQ40BdQVWWtonb9Af5IFpHz+6WU8wHxgjhaY84l2mlwIxu/IAqjxwvuMNrfHcoIdmwcITxZh1Dun8ckWTL8XDCxL4EHwhXj5tEOR51zE3wnvfNT1OfavtnIOpa35gx4oqpvb6748bPDbT1KScSrItsXRDelwZn5qAC/9oZwGZpF41F+uMPwty/X/P6AqWYz2UW/hoNIymFkcoU8HUkI2OtmlKW76bkJ+KHR+MW3uwOVQtZYkEolH/RYLlmMCJ2RhfD7MsKrrqOsOI7ROrMVp7bBzHkGT50vYi8hDGYRnb9jMgmHVuFejwQiFSFxOvN5aGo6dnmKV6fGXiTq3yUWSfwdC0/1K6OqT0giLByWLduLtEJSBIUWk8cWSIsx6CPh/TVrM3DPG7R1p6yuPyu9O13tRHYlLpGJOXbq6/eTLp6y9Jyh5f/mN3P1ydNfKH8iG1Sjj8pJbK2JAQ3zCnstHGpzFgjWncFqc1DuFIv/gJRact5fA7MnwjZMaexxhInq+4Thbl8=
  - DEBFULLNAME="Mir CI Bot"
  - DEBEMAIL="mir-ci-bot@canonical.com"
  - SPREAD_PATH=/tmp/spread
  matrix:
  - SYSTEM=ubuntu-16.04 VARIANT=amd64
  - SYSTEM=ubuntu-16.04 VARIANT=arm64
  - SYSTEM=ubuntu-17.10 VARIANT=amd64
  - SYSTEM=ubuntu-devel VARIANT=clang
  - SYSTEM=fedora-27 VARIANT=amd64

before_install:
- mkdir -p ${SPREAD_PATH}
- pushd "${SPREAD_PATH}"
- curl -s -O https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz
- tar xzvf spread-amd64.tar.gz
- popd

script:
- ${SPREAD_PATH}/spread -v linode:$SYSTEM:...:$VARIANT

jobs:
  include:
  - &ppa-upload
    stage: upload to ppa:mir-team
    env: RELEASE=16.04
    before_install:
    - openssl aes-256-cbc -K $encrypted_ba35384b250b_key -iv $encrypted_ba35384b250b_iv
      -in tools/bot-data.tar.xz.enc -out tools/bot-data.tar.xz -d
    - tar --extract --xz --file tools/bot-data.tar.xz --directory ${HOME}
    - git fetch --unshallow origin master:master
    script:
    - tools/ppa-upload.sh
    addons:
      apt:
        packages:
        - debhelper
        - devscripts
        - dput
        - fakeroot
        - python-launchpadlib
  - <<: *ppa-upload
    env: RELEASE=17.10
  - <<: *ppa-upload
    env: RELEASE=devel
