status = [
          "BuildAndTest (lxd:alpine-3.15:spread/build/alpine:amd64)",
          "BuildAndTest (lxd:ubuntu-22.04:spread/build/sbuild:ubuntu)",
          "BuildAndTest (lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_jammy)",
          "BuildAndTest (lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_arm64)",
          "BuildAndTest (lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_armhf)",
          "BuildAndTest (lxd:ubuntu-20.04:spread/build/ubuntu:clang)",
          "BuildAndTest (lxd:fedora-36:spread/build/fedora:amd64)",
          "BuildAndTest (lxd:fedora-37:spread/build/fedora:amd64)",
]
block-labels = [ "no-merge" ]
timeout-sec = 5400
delete-merged-branches = true
update_base_for_deletes = true
