[package]
name = "wayland_rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "build_script/main.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]
wayland-server.workspace = true
cxx.workspace = true
calloop.workspace = true
nix = { workspace = true, features = ["event"] }
log.workspace = true
wayland-scanner.workspace = true
wayland-backend.workspace = true
bitflags.workspace = true

[build-dependencies]
cxx-build.workspace = true
serde.workspace = true
quick-xml.workspace = true
quote.workspace = true
proc-macro2.workspace = true
prettyplease.workspace = true
syn.workspace = true
