[package]
name = "mir_platforms_evdev_rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx.workspace = true
input.workspace = true
libc.workspace = true
nix.workspace = true

[build-dependencies]
cxx-build.workspace = true
