name: Close Snaps

on:
  pull_request:
    types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v2

    # Could use canonical/actions/close-snap, but that would be quite verbose
    - name: Close obsolete channels
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
      run: |
        snapcraft close mir-libs "22/edge/pr${{ github.event.number }}" || true
        for snap in confined-shell miriway; do
          snapcraft close "$snap" "edge/mir-pr${{ github.event.number }}" || true
        done
        for snap in mir-test-tools ubuntu-frame; do
          snapcraft close "$snap" "24/edge/mir-pr${{ github.event.number }}" || true
        done
